vich_uploader:
    db_driver: orm

    mappings:
       taxon_image:
           uri_prefix: /images/taxons
           upload_destination: '%kernel.project_dir%/public/images/taxons'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
